### ISSUE TITLE
Multiple PTM prediction on the same residue

### ISSUE THREAD

**Issue by cvyaru** [yuyanislearning/MIND#9]
Hi, 

Is it possible to get predicted scores >0.5 for more than one PTM type, e.g. SUMO and Ubi in the same residue?

If yes, will all the positive (>0.5) predictions be printed in the file 'correct_predictions.csv', or only the one with the largest score per residue?

Thanks!

**Comment by yuyanislearning** [comment]
Hi, 
Yes, the model is designed to be able to predict multiple PTM on the same residue.
Both of them should be printed in the file.
